name: myenv
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - conda-forge::cartopy
  - conda-forge::geopandas
  - conda-forge::networkx
  - conda-forge::numpy
  - conda-forge::scipy
  - conda-forge::Shapely
  - conda-forge::fiona
  - conda-forge::jupyter
  - conda-forge::pygeos
  - conda-forge::rasterio
  - conda-forge::matplotlib
  - conda-forge::contextily
  - conda-forge::rasterstats
  - conda-forge::seaborn
  - conda-forge::jupyterlab
  - conda-forge::python-igraph
  - conda-forge::rtree 
  - conda-forge::shapely
  - cmake
  # - osmconvert: Manually download binaries from https://wiki.openstreetmap.org/wiki/Osmconvert#Windows => rename to osmconvert.exe => place the .exe in the osm folder created by osm_flex
  # - trail: Manually place the src folder in the ra2ce_multi|_network folder, and then import accordingly in .py files
  - pip:
    - geojson
    - igraph
    - pygeos
    - osmnx
    - damagescanner
    - snkit
    - osm-flex
    
    # trails
    
