name: myenv
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - conda-forge::cartopy
  - conda-forge::geopandas
  - conda-forge::networkx
  - conda-forge::numpy
  - conda-forge::scipy
  - conda-forge::Shapely
  # - conda-forge::fiona
  - pip:
    - geojson
    - osmnx
    - osm-flex
    # Manual install of osm-flex if gave error:
    ## activate ra2ce_multi_network_env
    ## pip install osm-flex 
    
    # trails
    
