name: ra2ce_multi_network_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - gdal=3.5.1
  - fiona
  # - geojson
  # - numpy
  # - pandas
  # - networkx
  # - scipy
  # - osmnx
  # - geopandas
  # - Shapely
  # - affine
  # - click
  # - geopy
  # - pyarrow
  # - rasterio
  # - rasterstats
  # - Rtree
  # - seaborn
  # - tqdm
  # Install poetry 1.3.2 (1.4.*) gives issues.
  # If this does not work then exclude it from the environment and install it manually
  # with: conda install -c conda-forge poetry=1.3.2
  - poetry=1.3.2
  - pip:
    - git+https://github.com/ElcoK/trails.git#egg=trails
    - git+https://github.com/osm-flex/osm-flex.git#egg=osm_flex
