name: ra2ce_multi
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - conda-forge::cartopy
  - conda-forge::geopandas
  - conda-forge::networkx
  - conda-forge::numpy
  - conda-forge::scipy
  - conda-forge::Shapely
  - conda-forge::fiona
  - conda-forge::jupyter
  - conda-forge::pygeos
  - conda-forge::rasterio
  - conda-forge::matplotlib
  - conda-forge::contextily
  - conda-forge::rasterstats
  - conda-forge::seaborn
  - conda-forge::jupyterlab
  - conda-forge::python-igraph
  - conda-forge::rtree 
  - conda-forge::shapely
  - conda-forge::triangle
  - cmake
  - conda-forge::python=3.10
  - conda-forge::gdal=3.5.1
  - conda-forge::fiona
  - conda-forge::pyarrow
  - conda-forge::momepy
  # Install poetry 1.3.2 (1.4.*) gives issues.
  # If this does not work then exclude it from the environment and install it manually
  # with: conda install -c conda-forge poetry=1.3.2
  - conda-forge::poetry=1.3.2
  # - osmconvert: Manually download binaries from https://wiki.openstreetmap.org/wiki/Osmconvert#Windows => rename to osmconvert.exe => place the .exe in the osm folder created by osm_flex
  # - trail: Manually place the src folder in the ra2ce_multi|_network folder, and then import accordingly in .py files
  - pip:
    - geojson
    - igraph
    - pygeos
    - osmnx
    - damagescanner
    - snkit
    - osm-flex
    
    # trails
    
